### ISSUE TITLE
Contributor Request

### ISSUE THREAD

**Issue by revett** [astro/ruby-collectd#8]
As discussed on Twitter ([tweet](https://twitter.com/astro1138/status/553192027811495937)) can you please make me a contributor.

**Github Username**
    
    revett

**Rubygems Profile**

    https://rubygems.org/profiles/revett

My email address can be found on Rubygems.

**Comment by astro** [comment]
Happy maintaining!

Attn: @julien51 (the only user I know of)

**Comment by julien51** [comment]
:D I hope there are more... because we do not use it anymore :(
